### ISSUE TITLE
Absence of detailed documentation

### ISSUE THREAD

**Issue by devfinwiz** [arm210402/encrypt-decrypt#1]
A README file would be good to have to have a better understanding of what the repo does and more importantly how it does so...

**Comment by arm21-afk** [comment]
Thank you for your feedback, I appreciate it. I understand the importance of having a clear README file for my repository, and I will definitely add it.
If you have any specific suggestions or areas of focus that you would like me to address in the README file, I would be happy to incorporate them. Once again, thank you for taking the time to provide me with this feedback.

**Comment by arm21-afk** [comment]
.
